name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'
  workflow_dispatch:

jobs:
  macos_tests:
    runs-on: macos-14
    strategy:
      matrix:
        xcode:
          - "15.4"
        command:
          - test
          - benchmarks
    steps:
      - uses: actions/checkout@v4
      - name: Select Xcode ${{ matrix.xcode }}
        run: sudo xcode-select -s /Applications/Xcode_${{ matrix.xcode }}.app
      - name: System
        run: system_profiler SPHardwareDataType
      - name: Run ${{ matrix.command }}
        run: make ${{ matrix.command }}

  ubuntu_tests:
    strategy:
      matrix:
        os: [ubuntu-20.04]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: swift build
      - name: Run tests
        run: swift test
